### ISSUE TITLE
registerValidator fails with "error response: 403 / error code: 1020"

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost-relay#155]
This are the error messages:

```
time="2022-09-23T10:30:47Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 403 / error code: 1020" method=registerValidator module=service numRegistrations=25 ua=Go-http-client/1.1 url="https://boost-relay.flashbots.net/eth/v1/builder/validators"
time="2022-09-23T10:30:47Z" level=info msg="http: POST /eth/v1/builder/validators 502" duration=0.017662955 method=POST module=service path=/eth/v1/builder/validators status=502
time="2022-09-23T10:30:59Z" level=debug msg="Checking relay status" module=service url="https://boost-relay.flashbots.net/eth/v1/builder/status"
time="2022-09-23T10:30:59Z" level=error msg="failed to retrieve relay status" error="HTTP error response: 403 / error code: 1020" module=service url="https://boost-relay.flashbots.net/eth/v1/builder/status"
time="2022-09-23T10:30:59Z" level=info msg="http: GET /eth/v1/builder/status 503" duration=0.011533301 method=GET module=service path=/eth/v1/builder/status status=503
```

**Comment by Ruteri** [comment]
Do we know which version of mev-boost is it?

**Comment by come-maiz** [comment]
From @metachris:
there was a rate limit validator registration calls / 5 min / IP
We've increased it.

I'll ask the operator to try again.

**Comment by metachris** [comment]
the rate limit was 40 calls / min / IP, now upped to 80. does it help?

**Comment by Pabs90** [comment]
From the logs it looks like the status check is still done every 30s without using the -relay-check explicitly. Removing that argument from startup gets rid of the 403/503 errors on the status check, not sure how that works out. However, even on 1.3.2 I still see the 403/502 on the registerValidator method on 3 separate instances.

**Comment by metachris** [comment]
Which country are the requests originating from?

**Comment by danspina1** [comment]
Hi @metachris the requests are originating from France

**Comment by metachris** [comment]
it look like cloudflare blocks the requests. are you still seeing 403s?

**Comment by Pabs90** [comment]
Yes, it looks like once every 6 minutes on a few instances, `time="2022-10-06T15:50:47Z" level=debug msg=registerValidator method=registerValidator module=service
time="2022-10-06T15:50:47Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 403 / error code: 1020" method=registerValidator module=service numRegistrations=25 ua=Go-http-client/1.1 url="https://boost-relay.flashbots.net/eth/v1/builder/validators"
time="2022-10-06T15:50:47Z" level=info msg="http: POST /eth/v1/builder/validators 502" duration=0.035003311 method=POST module=service path=/eth/v1/builder/validators status=502`

**Comment by metachris** [comment]
It looks like Cloudflare thinks your IP reputation is bad: https://community.cloudflare.com/t/community-tip-access-was-denied-error-code-1020/66439

Now we'd need to look at your setup, and which outgoing IP's you're using. Perhaps try rotating the IP / using a different one?

**Comment by metachris** [comment]
should be resolved, at least haven't seen any recent reports.

please comment to reopen

**Comment by nyetwurk** [comment]
We are still seeing intermittent 403 errors. Please consider removing bot protection from cloudflare; they're notoriously finicky and tend to come and go.
